---
Name: foxyroutes
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    'foxy//$Action/$ID/$Name': Dynamic\Foxy\Controller\FoxyController

---
Only:
  environment: 'dev'
---
SilverStripe\Control\Director:
  rules:
    'foxytest//$Action/$ID/$Name': Dynamic\FoxyStripe\Controller\DataTestController
